# Generated by Django 5.1.4 on 2024-12-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0011_alter_userprofile_type_alter_userprofile_website'),
        ('QuizGenWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfile',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuizApp.subject'),
        ),
    ]
