# Generated by Django 4.2.2 on 2023-06-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userquiz_date_userquiz_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
