# Generated by Django 4.2.2 on 2023-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(max_length=255)),
                ('type', models.CharField(choices=[('TEA', 'Teacher'), ('STU', 'Student')], max_length=3)),
            ],
        ),
    ]
