# Generated by Django 4.2.2 on 2023-07-16 08:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='attempt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.attempt'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='read_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rebuttal',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='review',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.IntegerField(choices=[(0, 'New assignment'), (1, 'New review requested'), (2, 'New feedback received')], default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.assignment'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
    ]
