# Generated by Django 4.2.4 on 2023-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_attempt_json_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='json_text',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='saved_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='saved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='submit_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='submit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
