# Generated by Django 4.2.4 on 2023-09-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_alter_attempt_json_text_alter_attempt_saved_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='feedback_blind',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Hide Reviewer'), (2, 'Hide Author'), (3, 'Double Blind')], default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='feedback_delay',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='feedback_reviewer',
            field=models.IntegerField(choices=[(0, 'Teacher assigned'), (1, 'Random assigned')], default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='feedback_type',
            field=models.CharField(choices=[('TEAC', 'Teacher review'), ('PEER', 'Peer review')], default='TEAC', max_length=4),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='generating_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='timer',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='seed',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
