# Generated by Django 4.2.4 on 2023-09-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0009_alter_assignment_deadline_alter_assignment_timer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='feedback_delay',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
