# Generated by Django 5.0.6 on 2024-05-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0010_alter_assignment_feedback_delay_alter_attempt_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('TEA', 'Teacher'), ('STU', 'Student'), ('ADM', 'Admin')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
